basePath: /inventory/v1
definitions:
  main.item:
    properties:
      id:
        type: integer
      name:
        type: string
      quantity:
        type: integer
      unit_price:
        type: number
    type: object
host: localhost:8080
info:
  contact:
    email: srga8641@colorado.edu
    name: Sreeram Ganesan
    url: https://sreeramganesan.com
  description: An inventory management API with Go using Gin framework.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://sreeramganesan.com
  title: Inventory API
  version: "1.0"
paths:
  /items:
    get:
      description: Responds with the list of all items as JSON.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.item'
            type: array
      summary: Get items array
      tags:
      - items
swagger: "2.0"
